version: '3.8'

services:
  spring-app:
    image: your_spring_app_image_name
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - mynetwork
    ports:
      - "8080:8080"

networks:
  mynetwork:
    driver: bridge